language: c
dist: trusty

branches:
  only:
  - master

before_install:
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get install -y mpich2
  - mpichversion
  - mpicc -show
  - which mpicc
  - wget https://parallel-netcdf.github.io/Release/pnetcdf-1.12.2.tar.gz 
  - tar -xzvf pnetcdf-1.12.2.tar.gz
  - pushd pnetcdf-1.12.2
  - ./configure --prefix=$HOME/PnetCDF --disable-fortran --silent MPICC=mpicc MPICXX=mpicxx
  - make -s LIBTOOLFLAGS=--silent V=1 -j4
  - make -s install
  - popd

script:
  - make PnetCDF_DIR=$HOME/PnetCDF
  # - mpiexec -n 16 valgrind --quiet --leak-check=full ./e3sm_io datasets/f_case_866x72_16p.nc
  # - mpiexec -n 16 valgrind --quiet --leak-check=full ./e3sm_io datasets/g_case_cmpaso_16p.nc
  - mpiexec -n 16 ./e3sm_io datasets/f_case_866x72_16p.nc
  - mpiexec -n 16 ./e3sm_io datasets/g_case_cmpaso_16p.nc

after_success:
  - make -s clean

notifications:
  email: false

